Добавляет стилизацию главной страницы
htmlacademy-htmlcss/1052685-gllacy-31 pull request #5
Opened 2021-06-02 15:09 UTC by nelmare

2021-06-02 19:40 UTC, Pakistanka requested changes

2021-06-02 19:40 UTC, Pakistanka commented on style.css
> +  url("./fonts/roboto.woff") format("woff");
url-ы должны стоять один под одним

2021-06-02 19:40 UTC, Pakistanka commented on style.css
> +
Файлы normalize.css и style.css должны лежать в папке css, а не в корне проекта - https://prnt.sc/13qslio

2021-06-03 11:44 UTC, nelmare commented on style.css
> +
Исправила

2021-06-03 19:45 UTC, merged